### PR TITLE
Django 2.0

### PR DESCRIPTION
**Pull request by fishilico**
Django 2.0 requires a minor update in the models. Add this version to tests in order to catch breaking changes.

### CODE REVIEW

**Comment by fishilico** [comment]
There is an issue with django-oidc-provider, which is not compatible with Django 2.0 yet. The library needs a fix: https://github.com/juanifioren/django-oidc-provider/pull/216
I will create a separate merge request for the first commit, and when django-oidc-provider will support Django 2.0, we will be able to merge this PR.

**Comment by fishilico** [comment]
django-oidc-provider 0.5.3 has been released. I have updated this pull request.

**Comment by vberger** [comment]
So, is there anything blocking us from a complete switch to django 2.0, now ?

**Comment by fishilico** [comment]
Yes, the server hosting the application only provides Python 2.7 or Python 3.2. It needs to be updated to the latest Debian release...

**Comment by fishilico** [comment]
By the way (before merging this), do we want to define a maximum supported Django version, that we would increment each time a new release occurs? (ie. does adding ``Django < 2.1`` make sense?)

**Pull request merged**
