### PR TITLE
Add development accounts JSON

### PR DESCRIPTION
**Pull request by fishilico**
Introduce a JSON file with test/development accounts, in order to test the import from dumps generated from `scripts/export_platal_to_json.py`.

TODO:
- [x] associate the password to the user account
- [x] associate "is_admin" with an admin role?

### CODE REVIEW

**Comment by vberger** [comment]
> associate "is_admin" with an admin role?

Why wouldn't we do that?

👍 for the code currently in the PR

**Comment by fishilico** [comment]
> Why wouldn't we do that?

Done.

**Comment by fishilico** [comment]
I imported email aliases but I don't know how to make Django use them to find a user to authenticate, in the login form. How?

**Comment by vberger** [comment]
We'll likely need to write our own `AuthenticationBackend` that does this ([relevant doc](https://docs.djangoproject.com/en/1.11/topics/auth/customizing/)).

It should be pretty straightforward. I can do this in an other PR after this one is merged if you don't have time for this.

**Pull request merged**
