### PR TITLE
Allow hrid and email aliases to authenticate

### LINKED ISSUE #6: Authenticate with a user alias
There are email aliases defined for each user. Allow using them when logging in.
cf. https://github.com/Polytechnique-org/xorgauth/pull/1#issuecomment-344155579

### PR DESCRIPTION
**Pull request by elinorbgr**
This uses a custom authentication backend with the following behavior:

- if the entered value does not contained an `@`, it attempts to log the user in using its hrid
- if it contains an `@`, it first attempts find the user with its `main_email`, and on failure tries to find the user using an email alias

fixes #6

### CODE REVIEW

**Review by rbarrois — APPROVED** [review]

**Comment by rbarrois** [comment]
But... but... Where are the tests?

**Comment by vberger** [comment]
Good point, I need to find again how to write those...

**Comment by vberger** [comment]
@rbarrois is that better ? :)

**Comment by fishilico** [comment]
Looks good to me, and as I want to use ``create_user`` for the tests that I introduced in https://github.com/Polytechnique-org/xorgauth/pull/21, I am merging it now. Thanks!

**Pull request merged**
